server:
  port: 8761


eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true


#  禁用eureka的自我保护机制
#  server:
#    enable-self-preservation: false