eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  #修改默认服务名称
#  instance:
#    instance-id: client-01
#    prefer-ip-address: true

server:
  port: 8763
spring:
  application:
    name: service-pay