eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  #修改默认服务名称
#  instance:
#    instance-id: client-01
#    prefer-ip-address: true

server:
  port: 8888
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /a/**
      url:  http://localhost:8762/
      serviceId: service-number
    api-b:
      path: /b/**
      url:  http://localhost:8763/
      serviceId: service-pay
swagger:
  butler:
    resources:
      api-a:
        name: service-number
      api-b:
        name: service-pay
